name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.0.0
        name: Checkout
      - uses: cachix/install-nix-action@v16
        name: Install Nix
      - uses: cachix/cachix-action@v10
        name: Set up Cachix
        with:
          name: evanrelf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build --print-build-logs
